const consultasImagemPersonalizada: { [destino: string]: string } = {
    "Rio Branco - AC": "Palácio Rio Branco - Rio Branco - AC",
    "Maceió - AL": "Praia do Francês - Maceió - AL",
    "Macapá - AP": "Fortaleza de São José - Macapá - AP",
    "Manaus - AM": "Teatro Amazonas - Manaus - AM",
    "Salvador - BA": "Elevador Lacerda - Salvador - BA",
    "Fortaleza - CE": "Praia do Futuro - Fortaleza - CE",
    "Brasília - DF": "Congresso Nacional - Brasília - DF",
    "Vitória - ES": "Convento da Penha - Vitória - ES",
    "Goiânia - GO": "Parque Flamboyant - Goiânia - GO",
    "São Luís - MA": "Parque Nacional Lençóis Maranhenses - São Luís - MA",
    "Cuiabá - MT": "Parque Mãe Bonifácia - Cuiabá - MT",
    "Campo Grande - MS": "Parque das Nações Indígenas - Campo Grande - MS",
    "Belo Horizonte - MG": "Praça da Liberdade - Belo Horizonte - MG",
    "Belém - PA": "Estação das Docas - Belém - PA",
    "João Pessoa - PB": "Praia de Tambaú - João Pessoa - PB",
    "Curitiba - PR": "Jardim Botânico - Curitiba - PR",
    "Recife - PE": "Marco Zero do Recife - Recife - PE",
    "Teresina - PI": "Encontro dos Rios - Teresina - PI",
    "Rio de Janeiro - RJ": "Cristo Redentor - Rio de Janeiro - RJ",
    "Natal - RN": "Morro do Careca - Natal - RN",
    "Porto Alegre - RS": "Usina do Gasômetro - Porto Alegre - RS",
    "Porto Velho - RO": "Estrada de Ferro Madeira-Mamoré - Porto Velho - RO",
    "Boa Vista - RR": "Praça das Águas - Boa Vista - RR",
    "Florianópolis - SC": "Ponte Hercílio Luz - Florianópolis - SC",
    "São Paulo - SP": "Avenida Paulista - São Paulo - SP",
    "Aracaju - SE": "Orla de Atalaia - Aracaju - SE",
    "Palmas - TO": "Praça dos Girassóis - Palmas - TO",
    "Paris - França": "Torre Eiffel - Paris - França",
    "Londres - Reino Unido": "Big Ben - Londres - Reino Unido",
    "Roma - Itália": "Coliseu - Roma - Itália",
    "Berlim - Alemanha": "Portão de Brandemburgo - Berlim - Alemanha",
    "Madri - Espanha": "Palácio Real - Madri - Espanha",
    "Lisboa - Portugal": "Torre de Belém - Lisboa - Portugal",
    "Atenas - Grécia": "Parthenon - Atenas - Grécia",
    "Viena - Áustria": "Palácio de Schönbrunn - Viena - Áustria",
    "Amsterdã - Países Baixos": "Museu Van Gogh - Amsterdã - Países Baixos",
    "Bruxelas - Bélgica": "Atomium - Bruxelas - Bélgica",
    "Oslo - Noruega": "Ópera de Oslo - Oslo - Noruega",
    "Estocolmo - Suécia": "Palácio Real de Estocolmo - Estocolmo - Suécia",
    "Copenhague - Dinamarca": "Palácio de Amalienborg - Copenhague - Dinamarca",
    "Helsinque - Finlândia": "Catedral de Helsinque - Helsinque - Finlândia",
    "Reiquiavique - Islândia": "Hallgrímskirkja - Reiquiavique - Islândia",
    "Moscou - Rússia": "Catedral de São Basílio - Moscou - Rússia",
    "Pequim - China": "Cidade Proibida - Pequim - China",
    "Tóquio - Japão": "Templo Senso-ji - Tóquio - Japão",
    "Seul - Coreia do Sul": "Palácio Gyeongbokgung - Seul - Coreia do Sul",
    "Bangkok - Tailândia": "Grande Palácio - Bangkok - Tailândia",
    "Hanói - Vietnã": "Templo da Literatura - Hanói - Vietnã",
    "Nova Délhi - Índia": "Porta da Índia - Nova Délhi - Índia",
    "Islamabad - Paquistão": "Mesquita Faisal - Islamabad - Paquistão",
    "Cabul - Afeganistão": "Mesquita Azul - Cabul - Afeganistão",
    "Teerã - Irã": "Torre Azadi - Teerã - Irã",
    "Bagdá - Iraque": "Mesquita Al-Kadhimiya - Bagdá - Iraque",
    "Riad - Arábia Saudita": "Centro do Reino - Riad - Arábia Saudita",
    "Abu Dhabi - Emirados Árabes Unidos": "Grande Mesquita Sheikh Zayed - Abu Dhabi - Emirados Árabes Unidos",
    "Cairo - Egito": "Pirâmides de Gizé - Cairo - Egito",
    "Nairóbi - Quênia": "Parque Nacional de Nairóbi - Nairóbi - Quênia",
    "Pretória - África do Sul": "Union Buildings - Pretória - África do Sul",
    "Luanda - Angola": "Fortaleza de São Miguel - Luanda - Angola",
    "Maputo - Moçambique": "Estação Central de Maputo - Maputo - Moçambique",
    "Brasília - Brasil": "Congresso Nacional - Brasília - Brasil",
    "Buenos Aires - Argentina": "Casa Rosada - Buenos Aires - Argentina",
    "Santiago - Chile": "Palácio de La Moneda - Santiago - Chile",
    "Lima - Peru": "Plaza Mayor - Lima - Peru",
    "Bogotá - Colômbia": "Cerro Monserrate - Bogotá - Colômbia",
    "Quito - Equador": "Cidade Antiga - Quito - Equador",
    "Caracas - Venezuela": "Parque Nacional El Ávila - Caracas - Venezuela",
    "Montevidéu - Uruguai": "Palácio Salvo - Montevidéu - Uruguai",
    "Assunção - Paraguai": "Palácio de los López - Assunção - Paraguai",
    "La Paz - Bolívia": "Praça Murillo - La Paz - Bolívia",
    "Cidade do México - México": "Zócalo - Cidade do México - México",
    "Ottawa - Canadá": "Parlamento do Canadá - Ottawa - Canadá",
    "Washington, D.C. - Estados Unidos": "Capitólio dos EUA - Washington, D.C. - Estados Unidos",
    "Havana - Cuba": "Capitólio de Havana - Havana - Cuba",
    "Kingston - Jamaica": "Museu Bob Marley - Kingston - Jamaica",
    "Canberra - Austrália": "Parlamento da Austrália - Canberra - Austrália",
    "Wellington - Nova Zelândia": "Parlamento da Nova Zelândia - Wellington - Nova Zelândia"
  };
  
  export default consultasImagemPersonalizada;
  